# Generated by Django 5.2.4 on 2025-07-03 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('adet', models.IntegerField()),
                ('renk', models.CharField(max_length=100)),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcalar', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='Fotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='parca_fotograflari/')),
                ('parca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='envanter.parca')),
            ],
        ),
    ]
