# Generated by Django 5.2.4 on 2025-07-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parca',
            name='ad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
